language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "Tools"
      install: true
      script: sh ci/tools.sh
    - name: "x86_64-unknown-linux-gnu"
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "i686-unknown-linux-gnu"
      env: TARGET=i686-unknown-linux-gnu
    - name: "i686-apple-darwin"
      env: TARGET=i686-apple-darwin NO_DOCKER=1
      os: osx
      osx_image: xcode10
    - name: "x86_64-apple-darwin"
      env: TARGET=x86_64-apple-darwin NO_DOCKER=1
      os: osx
      osx_image: xcode10
      install: true

install: travis_retry rustup target add $TARGET
script:
  - cargo generate-lockfile
  - sh ci/run.sh "${TARGET}"
